# Generated by Django 5.0.3 on 2024-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menueasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('B', 'Basico'), ('I', 'Intermediario'), ('A', 'Acancado')], default='B', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='complementary',
            name='item',
        ),
        migrations.RemoveField(
            model_name='subcomplementary',
            name='complementary',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Complementary',
        ),
        migrations.DeleteModel(
            name='SubComplementary',
        ),
    ]
